name: CI/CD

# Triggers the workflow on push or pull request events
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  # Build and test the project
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  # Deploy to a hosting service (e.g., GitHub Pages)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install  
    - run: npm run deploy
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
  
